---
- hosts: all
  sudo: yes
  tasks:
   - name: Set mailname
     lineinfile: dest=/etc/mailname regexp='.*' line="debian.local"
   - name: Set hosts
     lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1' line='127.0.1.1 debian.local debian-7'
   - name: Add Suoer postgres
     lineinfile: dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
   - name: Install packages
     apt: >
       pkg={{ item }}
       state=installed
       update_cache=yes
     with_items:
       - build-essential
       - nginx
       - git
       - python-dev
       - python-pip
       - postfix
       - python-psycopg2
       - python-django
       - postgresql
       - libpq-dev
       - sudo
       - supervisor 
   - name: Add Db user
     postgresql_user: >
       name=vagrant
       role_attr_flags=CREATEDB
     sudo: true
     sudo_user: postgres
   - name: Add Db
     postgresql_db: >
       name=vagrant
       owner=vagrant
     sudo: true
     sudo_user: postgres
   - name: Add supervisordconf
     template: >
        src=supervisor.conf.j2
        dest=/etc/supervisor/conf.d/vagrant.conf
        mode=644
   - name: Add nginx conf
     template: >
        src=nginx-default.j2
        dest=/etc/nginx/sites-available/default
        mode=644
     notify: 
      - restart nginx
   - name: Boostrap project
     shell: chdir=/vagrant python bootstrap.py
     sudo: false
   - name: Buildout project
     command: chdir=/vagrant "./bin/buildout"
     sudo: false
     notify: 
      - restart supervisord
  handlers:
   - name: restart nginx
     service: name=nginx state=restarted
   - name: restart supervisord
     supervisorctl: name=vagrant state=restarted
