language: python
python:
  - 2.7
before_script:
  - export DISPLAY=:99.0
install:
  - python setup.py dev
  - pip install zc.buildout
  - buildout
script:
  - DJANGO_SETTINGS_MODULE={{cookiecutter.project_name}}.settings bin/nosetests
  - bin/gulp test
