language: python
python:
  - 2.7
before_script:
  - export DISPLAY=:99.0
install:
  - python setup.py dev
  - pip install zc.buildout
  - buildout install node sh
script:
  - DJANGO_SETTINGS_MODULE=repo_name.settings nosetests
  - gulp test
